version: "3"
services:
    mysql:
        image: mysql
        container_name: db
        environment:
            - MYSQL_ROOT_PASSWORD=1
        ports:
            - 3306:3306
        volumes:
            - mysqldata:/var/lib/mysql
    web:
        build: .
        depends_on:
            - mysql
        ports: 
            - 8080:8000
        volumes:
            - ./:/var/www/laravel
volumes:
    mysqldata: